# Generated by Django 3.2.7 on 2021-09-24 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_backimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='image_count',
            field=models.IntegerField(default=0),
        ),
    ]
