# Generated by Django 3.2.7 on 2021-09-24 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_customuser_image_count'),
        ('main', '0003_userimage'),
    ]

    operations = [
    ]
